# Up to this point, we have just been working with requests that display information from the server to the user. What if a request involves the client sending information to the server? The modern internet is user-driven; much of the actual content of a website is generated by the users of a website. How does a user provide content to a website? One word: FORMS. HTML forms are the way in which users are able to pass data to the back end of a website, where the data can then be processed and stored. Processing form data correctly is a huge part of what it takes to become a back-end developer.

# Let's create a new project called form_test. We'll use this in the next few sections. Go ahead and create the server.py file and a directory called templates.

# 1.) create and set up the server.py file.

#2.) make our html have a form on it
    # <h1>Index Page</h1>
    # <h3>Create a User</h3>
    # <form action='/users' method='post'>
    #     <label for='name'>Name:</label>
    #     <input type='text' name='name'>
    #     <label for='email'>Email:</label>
    #     <input type='text' name='email'>
    #     <input type='submit' value='create user'>
    # </form>


#         action attribute
# This is the route that will process the form (not the one that shows the form--that's "/"). We'll set this up shortly.

#         method attribute
# Our options are GET and POST; most likely, we'll want this to be a POST request (but if you don't set it, the default is GET)

#         input elements
# These are the parts of the form that actually gather data from the user. Check here for type options. Also check here for other form elements like select (dropdowns) and textarea. Each element should have a unique value for its name attribute.

#         a way to submit the form
# This can either be <input type='submit'> or <button>Submit</button>, but NOT <input type='button'>.

# 3.) Finally, let's determine what should happen when the form is actually submitted. We indicated above, with the action attribute, that this POST request would be handled with the route /users, so let's add this to our server:

# from flask import Flask, render_template, request, redirect # added request
            
# @app.route('/users', methods=['POST'])
# def create_user():
#     print("Got Post Info")
#     print(request.form)
#     # Never render a template on a POST request.
#     # Instead we will redirect to our index route.
#     return redirect('/')



# Specifying Allowed Methods: methods=['POST']
    # If we don't provide a value for methods, only GET requests are allowed. Everything we've done up to this point have been GET requests, so it has been okay, but since we want this method to handle POST requests, we must specify that. Notice it is a list--it's possible to provide more than one value.

# Accessing Data: request.form['name_of_input']
    # The name we gave to each HTML input was significant. On the server-side, we can access data that was input into a field from a user through the request.form dictionary by providing the name of the input as the key. To see what's in your request object, try printing request.form.

# Lastly, note that the type of anything that comes in through request.form will be a "string" no matter what. If you want that value to be identified as an actual number you'll have to type cast it.